---
  - name: Ensure directory is there for storing k8s kubeconfig
    file:
      path: "{{ k8skubeconfig_dir }}"
      state: directory
    delegate_to: localhost

  - name: Download k8s kubeconfig file
    command: epicctl api get -u "/api/v2/k8skubeconfig" -n {{ common.name }} -p {{ common.platform }} -o {{ k8skubeconfig_dir }}/kubeconfig
    register: res
    failed_when: res.rc != 0