---
- name: Ensure pre-checks runs successfully.
  shell: "{{ bundle_dir }}/{{ bin_file }} --prechecks-only"
  changed_when: false
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "{{ res.stdout }}"
