---
  - name: Prepare input file for epicctl.
    template:
      src: controller.j2
      dest: /tmp/controller.yml
      mode: 0640
  
  - name: Run epicctl command to setup and configure controller node
    command: epicctl op -f /tmp/controller.yml -n "OnPremSetup"
    register: res
    #failed_when: res.rc != 0
    failed_when: false

  - debug:
      msg: "{{ res.stdout }}"
