---
- name: Prepare input file for epicctl.
  template:
    src: k8shosts.j2
    dest: "/tmp/{{ common.name }}_k8shosts.yml"
    mode: 0777
  
- name: Run epicctl command to setup and configure controller node
  command: "epicctl op -f /tmp/{{ common.name }}_k8shosts.yml -n {{ common.name }}"
  register: res
  failed_when: res.rc != 0
  #failed_when: false

- debug:
    msg: "{{ res.stdout }}"
