---
 
- name: Prepare configure air gap input file for epicctl.
  template:
    src: configure_airgap.j2
    dest: "/tmp/{{ common.name }}_configure_air_gap.json"
    mode: 0777
 
 curl -X PUT "http://16.143.22.204:8080/api/v2/config/k8s" -H "accept: */*" -H "X-BDS-SESSION: /api/v1/session/1bb537bf-719a-4ec6-b5d5-06de98921348" -H "Content-Type: application/json" -d "{\"airgap_parameters\":{\"container_repo_url\":\"string\",\"container_repo_username\":\"string\",\"container_repo_password\":\"string\",\"is_secure_container_repo\":true,\"container_repo_client_certificate\":\"string\",\"baseurl\":\"string\",\"repo_gpg_key\":\"string\",\"rpm_gpg_key\":\"string\"}}"
 
- name: Run epicctl command to configure for air gap installation
  command: 'epicctl api put -a -u /api/v1/install/?install_ha -f /tmp/{{ common.name }}_configure_ha.json -p {{ common.platform }} -n {{ common.name }}'
  register: res
  failed_when: res.rc != 0
  #failed_when: false

- debug:
    msg: "{{ res.stdout }}"
     
