---
 
- name: Prepare configure air gap input file for epicctl.
  template:
    src: configure_airgap.j2
    dest: "/tmp/{{ common.name }}_configure_air_gap.json"
    mode: 0777
  
- name: Run epicctl command to configure for air gap installation
  command: 'epicctl api put -a -u /api/v1/install/?install_ha -f /tmp/{{ common.name }}_configure_ha.json -p {{ common.platform }} -n {{ common.name }}'
  register: res
  failed_when: res.rc != 0
  #failed_when: false


- debug:
    msg: "res.stdout"
     
