---
 
- name: Prepare configure air gap input file for epicctl.
  template:
    src: configure_airgap.j2
    dest: "/tmp/{{ common.name }}_configure_air_gap.json"
    mode: 0777
 
- name: Configure platform for air gap
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/config/k8s
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ lookup('file','/tmp/api_session_id') }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: PUT
    body_format: json
    body: "{{ lookup('file','/tmp/CICL_configure_airgap.json') }}"
    status_code: 204
  register: airgap_res
  #failed_when: res.status != 200   

- debug:
    msg: "Airgap Configuration Result: {{ airgap_res.status }}"
     
