---
- name: Run epicctl command to destroy the specified platform
  command: "epicctl -n {{ common.name }} -p {{ common.platform }} destroy"
  register: res
  #failed_when: res.rc != 0
  failed_when: false

