---
- name: Copy epicctl to the target host
  copy: 
    src: "{{ common.bin_dir }}epicctl"
    dest: "/usr/local/bin/epicctl"
    owner: root
    group: root
    mode: preserve

- name: Prepare input file for epicctl.
  template:
    src: platform.j2
    dest: "/tmp/{{ common.name }}_platform.yml"
    mode: 0777
  
- name: Run epicctl command to setup and configure controller node
  command: "epicctl op -f /tmp/{{ common.name }}_platform.yml -n {{ common.name }}"
  register: res
  #failed_when: res.rc != 0
  failed_when: false

- debug:
    msg: "{{ res.stdout }}"
