---
- name: Copy the bin file from the automation server to the target server.
  synchronize: 
    src: "{{ bundles_dir }}/{{ bin_file }}"
    dest: "{{ bundles_dir }}/{{ bin_file }}"
  delegate_to: Automation

- name: Ensure pre-checks runs successfully.
  shell: "{{ bundles_dir }}/{{ bin_file }} --prechecks-only"
  changed_when: false
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "{{ res.stdout }}"
