---
  - name: Create k8s cluster with epicctl and rest api.
    command: epicctl api post -u "/api/v2/k8scluster/" -f /tmp/create_k8scluster.json -n "OnPremSetup" -p {{ common.platform }} -o /tmp/post-response.json
    register: res
    failed_when: res.rc != 0

  - debug:
     msg: "{{ res.stdout }}"
  
  - name: Check if response file exists.
    stat:
      path: /tmp/post-response.json
    register: output

  - name: Read response json file created during cluster creation
    set_fact:
      jsonResp: "{{ (lookup('file', '/tmp/post-response.json') | from_json)['location'] }}"
    when: output.stat.exists == True

  - name: Poll the status of cluster creation by making get call to /api/v2/k8scluster/k8scluster_id
    command: epicctl api get -u {{ jsonResp }} -n "OnPremSetup" -p {{ common.platform }} -o /tmp/get-response.json
    vars:
      getResp: "{{ (lookup('file', '/tmp/get-response.json') | from_json)['status'] }}"
    register : res
    failed_when: res.rc != 0
    changed_when: false
    retries: 30
    delay: 60
    until:  '"ready" == getResp'

  - debug:
      msg: "polling task finished"

