---
  - name: k8s tenant LCM.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-tenant
        vars:
          createtenant: true
          updatetenant: false
          deletetenant: false
          get_kubeconfig: true