---
  - name: Add k8s-hosts into cluster and install bundle.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-worker
        vars:
          addhosts: true

  - name: Delete k8s-hosts from cluster.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-worker
        vars:
          deletehosts: false
          delete_pools:
            - host: 10.1.10.22
